name: testing-webflow
on: ['push', 'workflow_run']
jobs:
    testing-job-1:
        runs-on: ubuntu
        steps:
            - name: download the source code
              uses: actions/checkout@v4
            - name: install node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: install dependencies
              run: npm install
            - name: run test
              run: npm run test

    testing-job-2:
        needs: testing-job-1
        runs-on: ubuntu
        steps:
            - name: download the source code
              uses: actions/checkout@v4
            - name: install node
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: install dependencies
              run: npm install
            - name: build app
              run: npm run build
            
            - run: echo "Node app deployed"


            